CREATE DATABASE IF NOT EXISTS NcSalesTax;

USE NcSalesTax;

CREATE TABLE IF NOT EXISTS County (
	Id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	County VARCHAR(30) NOT NULL,
	TaxRate DECIMAL(5,2) NOT NULL
);

INSERT INTO County (County, TaxRate)
VALUES
	("Alamance", 6.75),
	("Alexander", 7),
	("Alleghany", 6.75),
	("Anson", 7),
	("Ashe", 7),
	("Avery", 6.75),
	("Beaufort", 6.75),
	("Bertie", 7),
	("Bladen", 6.75),
	("Brunswick", 6.75),
	("Buncombe", 7),
	("Burke", 6.75),
	("Cabarrus", 7),
	("Caldwell", 6.75),
	("Camden", 6.75),
	("Carteret", 7),
	("Caswell", 6.75),
	("Catawba", 7),
	("Chatham", 7),
	("Cherokee", 7),
	("Chowan", 6.75),
	("Clay", 7),
	("Cleveland", 6.75),
	("Columbus", 6.75),
	("Craven", 6.75),
	("Cumberland", 7),
	("Currituck", 6.75),
	("Dare", 6.75),
	("Davidson", 7),
	("Davie", 6.75),
	("Duplin", 7),
	("Durham", 7.5),
	("Edgecombe", 7),
	("Forsyth", 7),
	("Franklin", 6.75),
	("Gaston", 7),
	("Gates", 6.75),
	("Graham", 7),
	("Granville", 6.75),
	("Greene", 7),
	("Guilford", 6.75),
	("Halifax", 7),
	("Harnett", 7),
	("Haywood", 7),
	("Henderson", 6.75),
	("Hertford", 7),
	("Hoke", 6.75),
	("Hyde", 6.75),
	("Iredell", 6.75),
	("Jackson", 7),
	("Johnston", 6.75),
	("Jones", 7),
	("Lee", 7),
	("Lenoir", 7),
	("Lincoln", 7),
	("Macon", 6.75),
	("Madison", 7),
	("Martin", 7),
	("Mcdowell", 6.75),
	("Mecklenburg", 7.25),
	("Mitchell", 6.75),
	("Montgomery", 7),
	("Moore", 7),
	("Nash", 7),
	("New Hanover", 7),
	("Northampton", 6.75),
	("Onslow", 7),
	("Orange", 7.5),
	("Pamlico", 6.75),
	("Pasquotank", 7),
	("Pender", 6.75),
	("Perquimans", 6.75),
	("Person", 7.5),
	("Pitt", 7),
	("Polk", 6.75),
	("Randolph", 7),
	("Richmond", 6.75),
	("Robeson", 7),
	("Rockingham", 7),
	("Rowan", 7),
	("Rutherford", 7),
	("Sampson", 7),
	("Scotland", 6.75),
	("Stanly", 7),
	("Stokes", 6.75),
	("Surry", 7),
	("Swain", 7),
	("Transylvania", 6.75),
	("Tyrrell", 6.75),
	("Union", 6.75),
	("Vance", 6.75),
	("Wake", 7.25),
	("Warren", 7),
	("Washington", 6.75),
	("Watauga", 6.75),
	("Wayne", 6.75),
	("Wilkes", 7),
	("Wilson", 7),
	("Yadkin", 6.75),
	("Yancey", 6.75);
